### PR TITLE
Convert do while loops in genmegqblh to bounded do loops, v3

### PR DESCRIPTION
**Pull request by wyphan**

### CODE REVIEW

**Comment by efdazedo** [comment]
Perhaps you can consider storing only the actually needed "i" values in an array and take advantage of this?  One idea is to perform zgemm related to "b1" for multiple values of "i" together so that it becomes a true matrix-matrix operation and not just matrix-vector multiply.

**Comment by wyphan** [comment]
@efdazedo I like that idea. Now, performance-wise, which way is better to implement it?
1. Modify `ntranblhloc(:,:)` (which currently contains the number of `i` loops == `n1`) into `ntranblhloc(1:2,:,:)` where the first element `ntranblhloc(1,iband,ikloc)` is the starting `i` index and the second element is the number of loops `n1`?
2. Create a new allocatable array variable, say, `idxtranblhloc(1:nstsv,1:nkloc)`, to store the starting `i` indices?

Edit: clarified wording

**Comment by wyphan** [comment]
Please ignore these 4 commits (045ad9c, 2ec9ebf, b4b70a5, 98ec636), which are only quality-of-life modifications to the build system (issue #5), and have nothing to do with the do while loop conversion. They do make my life easier though; I think I'm now one step closer to automated builds and tests...

**Comment by wyphan** [comment]
It's ready now. Looks like it was off by one because I didn't insert the `WRITE` commands at the correct position.

**Pull request merged**
